### ISSUE TITLE
Use new field instead of deprecated ones for determining "isMobile"

### ISSUE THREAD

**Issue by paulrutter** [ankushs92/Browscap4j#17]
See https://github.com/browscap/browscap/wiki/Resource%3A-User-Agents-Database.
I just noticed that this project still uses field "32" (isMobileDevice), but this is deprecated.
Please use "Device_Type" instead.

Thanks!

**Comment by ankushs92** [comment]
Thank you very much for pointing this out. Also, since I am a bit short of time these days, I won't be able to accept your pull request just yet. I'll be going over this project again on the weekend, make some changes, accept your pull request and then release a new version.

**Comment by paulrutter** [comment]
No problem, thanks 👍

**Comment by paulrutter** [comment]
-
