### ISSUE TITLE
Browscap constructor via InputStream

### ISSUE THREAD

**Issue by damir-manapov** [ankushs92/Browscap4j#20]
Its unavailable to access File from jar. At the same time Browscap uses File only for getting InputStream. It would be great to add constructor that get InputStream directly

**Comment by ankushs92** [comment]
As of now I don't have any plans to do that. I am aware of this problem but I want to keep this project very minimal. There's a workaround to this problem. I am copy pasting from one of my projects : 

```groovy
@Configuration
class BrowscapConfig {
    @Autowired
    ResourceLoader resourceLoader

    @Bean
    Browscap browscap(){
        def is = resourceLoader.getResource("classpath:/browscap.csv").getInputStream()
        String targetFile = resourceLoader.getResource("classpath:browscap.csv").getFilename()
        def file = new File(targetFile)
        FileUtils.copyInputStreamToFile(is, file);
        new Browscap(file)
    }
}
```

For `FileUtils`, Apache commons-io is used. Ofcourse this snippet works only for Spring boot, but you get the idea.
